(**  
API Test - Handlers to Call the common Functions used in API Test
@Version 1.0 23/08/2023 

"This software is copyright Keysight Technologies, Inc. and licensed under the terms of Keysight’s End User License Agreement. Terms of Keysight’s EULA may be found here: www.keysight.com/find/sweula By using this Software, you agree to the terms of the Keysight EULA."
**)

API_Post
API_Post_4
API_Post_5

to API_Post content
	//calling the python exe file
	put ResourcePath("Post_a_Content_on_Twitter.exe") into PythonAPIExe
	shell "c:\windows\system32\cmd.exe", "/c"&&PythonAPIExe&&quote&content&quote
end API_Post

to API_Post_4 
	//calling the api_post function to create a  post in twitter by passing input
	"Tests/Scenario".dateandtime
	set global context to datafunctions.CollectData("Post4")
	API_Post global context && Global UniqueValues
	insert global UniqueValues into universal UniqueValuesList
	wait 3
end API_Post_4

to API_Post_5 
	//calling the api_post function to create a  post in twitter by passing input
	"Tests/Scenario".dateandtime
	set global context to datafunctions.CollectData("Post5")
	API_Post global context && Global UniqueValues
	insert global UniqueValues into universal UniqueValuesList
end API_Post_5
